canonical/starflow

- .github/workflows/scan-python.yaml
- README.md
Examples of this working:
1. https://github.com/canonical/craft-platforms/pull/55 (https://github.com/canonical/craft-platforms/actions/runs/11040304469?pr=55)
2. https://github.com/canonical/charmcraft/pull/1924 (https://github.com/canonical/charmcraft/actions/runs/11042023040/job/30673655288?pr=1924)
> feat: Python project scan reusable workflow

- snap-publish/action.yaml
https://canonical-snapcraft.readthedocs-hosted.com/en/stable/reference/changelog/#id6
> fix: --platform no longer allowed in snapcraft

- .github/workflows/scan-python.yaml
- README.md
This allows disabling of uv.lock exporting (needed because uv cannot always export to requirements.txt) and adds a trivy scan using a uv sync created virtual environment.
> feat(scan-python): more configurable uv

- .github/renovate.json5
- .github/workflows/self-test-renovate.yaml
- README.md
- renovate.json5
The renovate GitHub app doesn't like symlinks, which isn't something that running renovate locally catches. This changes the renovate config to simply extend the renovate base config we have.
This limits us because our per-repo renovate config can't be different from the base config for this repo, but trying to link renovate to inherit from a different config file in the same repository has just found a bunch of issues in renovate.
Fixes #25
> fix!(renovate): move to a standard location

- .github/workflows/policy.yaml
It doesn't make sense to run the CLA checker once we're already on `main` and it fails anyway.
This returns us back to the [standard method](https://github.com/canonical/has-signed-canonical-cla) which is to just run on PRs.
> fix: only run CLA check on pull requests

- .github/workflows/lint-python.yaml
- .github/workflows/scan-python.yaml
- .github/workflows/self-test-qa.yaml
- .github/workflows/test-python.yaml
- Update astral-sh/setup-uv to v5, supporting declaring the python version wanted in the venv.
- Use the python-version to create a venv with the requested python version
- Enable re-running a failed job if another one failed by disabling fail-fast.
> fix: Properly set python version for uv

- .github/workflows/test-python.yaml
- Makefile
This should ensure the fast tests run in the correct Python versions.
> fix(test-python): correct versions

- .github/workflows/self-test-qa.yaml
- .github/workflows/test-python.yaml
This allows the lowest-dependencies Python platform to contain a list of tags.
It keeps the same default of `ubuntu-20.04`, which [succeeds here](https://github.com/canonical/starflow/actions/runs/13120125732/job/36603888180?pr=43), but also allows a list of tags like `["jammy", "arm64"]`, which [succeeds here](https://github.com/canonical/starflow/actions/runs/13120125732/job/36603890404?pr=43).
The motivation is to allow craft-application to test on the lowest versions: https://github.com/canonical/craft-application/actions/runs/13083693096/job/36601983812?pr=622
> feat(test-python): allow arrays for lowest python platform

- .github/workflows/test-python.yaml
This is in response to Focal being turned off on Github Runners: https://github.com/actions/runner-images/issues/11101
> fix(test-python): switch the default min python platform to 22.04

- .github/workflows/test-python.yaml
The runners are not guaranteed to have a valid apt cache, so call `apt update` before `make setup-tests` (which runs `install-build-deps`).
> ci: update apt before installing build deps

- renovate.json5
This configures Renovate to ignore certain packages.
The two ignored currently are:
- python-apt (version is tightly coupled to the base OS) https://github.com/canonical/craft-sd/pull/27
- pygit2 (version is tightly coupled to libgit2, for which we use the base)
> ci(renovate): ignore certain packages

- renovate.json5
This adds the starcraft-reviewers team to all renovate PRs automatically.
> feat(renovate): add starcraft-reviewers as default reviewers

- .github/workflows/self-test-qa.yaml
- .github/workflows/test-python.yaml
- Makefile
- README.md
This allows filtering test runs by markers, allowing the splitting of tests into multiple jobs.
craft-providers will use this so we can separate the various categories of slow tests (lxd, multipass, other)
View this in use at: https://github.com/canonical/craft-providers/actions/runs/15478603156/job/43579839334?pr=748
> feat(test-python): allow filtering by markers

- .github/workflows/self-test-setup.yaml
- .github/workflows/test-python.yaml
- setup-python-runner/README.md
- setup-python-runner/action.yaml
This moves the setup for Python runners to its own action so it can be reused across workflows.
> feat: setup python runner as its own action

- .github/workflows/lint-python.yaml
This is needed because canonical-sphinx uses [the git history](https://github.com/mgeier/sphinx-last-updated-by-git) to generate timestamps.
Example failure: https://github.com/canonical/starbase/actions/runs/16953811410/job/48051792476?pr=426#step:6:91
> fix(lint-python): fetch history

- renovate.json5
For whatever reason "$default" is including hotfix branches, so we're explicitly changing it to only update on main.
> fix(renovate): make renovate quieter on hotfix branches

- renovate.json5
Currently Renovate adds a label called `dependencies` to any PR it opens, but all of our other labels capitalize each word.
Once this is merged, a PR will be put up in the repo automation repository to codify this label and stop the bot from deleting it from all of the Renovate PRs.
> style(ci): make renovate label consistent with other starcraft labels

- .github/workflows/lint-python.yaml
Changes the lint-python job to install linters in parallel.
> feat(lint-python): install linters in parallel

- .github/workflows/test-python.yaml
Changes the configuration jobs so `make setup-tests` runs with unlimited jobs rather than a single job.
> feat(test-python): setup in parallel

- .github/workflows/self-test-qa.yaml
- .github/workflows/test-python.yaml
- Makefile
- README.md
This allows us to pass an environment variable to craft-parts to tell it not to install the plugin dependencies unless we're actually testing plugins.
Real use-case: https://github.com/canonical/craft-parts/pull/1275/files
> feat(test-python): allow extra environment variables during setup
